{% set name = "ipyfilechooser" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41df9e4395a924f8e1b78e2804dbe5066dc3fdc233fb07fecfcdc2a0c9a7d8d3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipywidgets
    - python >=3.6

test:
  imports:
    - ipyfilechooser

about:
  home: https://github.com/crahan/ipyfilechooser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python file chooser widget for use in Jupyter/IPython in conjunction with ipywidgets
  dev_url: https://github.com/crahan/ipyfilechooser

extra:
  recipe-maintainers:
    - crahan
