{% set name = "ipyfilechooser" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17bd649028bd2cc524a14c2e571ac8130d3f2fdf11ab6400f79330c5e632c88b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipywidgets
    - python >=3.6

test:
  imports:
    - ipyfilechooser

about:
  home: https://github.com/crahan/ipyfilechooser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python file chooser widget for use in Jupyter/IPython in conjunction with ipywidgets
  dev_url: https://github.com/crahan/ipyfilechooser

extra:
  recipe-maintainers:
    - crahan
